spring:
  application:
    name: poc-wallet-backend
  data:
    mongodb:
      uri: ${MONGO_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  auth:
    force-mfa: ${AUTH_FORCE_MFA:true}
  jwt:
    secret: ${JWT_SECRET}
    access-token-expires-minutes: ${JWT_EXPIRES_MIN:20}
    temp-token-expires-minutes: ${MFA_TEMP_EXPIRES_MIN:5}
